import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          "English": "English",
          'Choose Language': 'Choose Language',
          'Sign in to your account': 'Sign in to your account',
          'Phone Number': 'Phone Number',
          'Pin': 'Pin',
          'LOGIN': 'LOGIN',
          "Don't have an account? ": "Don't have an account? ",
          "SIGNUP": "SIGNUP",
          "Create your account": "Create your account",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Select your Gender": "Select your Gender",
          "Male": "Male",
          "Female": "Female",
          "Confirm Pin": "Confirm Pin",
          "Pin (Must be atleast 6 characters)":
              "Pin (Must be atleast 6 characters)",
          "Select an organization": "Select an organization",
          // "Confirm OTP": "Confirm OTP",
          "I understood the terms and policies.":
              "I understood the terms and policies.",
          "Have an account?": "Have an account?",
          "If you didn't get the message tap the resend button bellow.":
              "If you didn't get the message tap the resend button bellow.",
          "Loanable Fund": "Loanable Fund",
          "Bronze": "Bronze",
          "Silver": "Silver",
          "Gold": "Gold",
          "Premium": "Premium",
          "Members": "Members",
          "Transactions": "Transactions",
          "Loans": "Loans",
          "Awareness": "Awareness",
          "Start": "Start",
          "Meetings": "Meetings",
          "Tip of the day": "Tip of the day",
          "stay informed": "stay informed",
          "Recent updates": "Recent updates",
          "Total saving": "Total saving",
          "Total Social Fund": "Total Social Fund",
          "Total Loan Disbursed": "Total Loan Disbursed",
          "Total Loan Repayed": "Total Loan Repayed",
          "Total Social Fund released": "Total Social Fund released",
          "Total members": "Total members",
          "Proxy": "Proxy",
          "GROUP_ADMIN": "GROUP_ADMIN",
          "Manager": "Manager",
          "saving": "saving",
          "Loan Despersal": "Loan Despersal",
          "Loan Repayment": "Loan Repayment",
          "Social Funds": "Social Funds",
          "All Transactions": "All Transactions",
          "Pending ": "Pending ",
          "Active": "Active",
          "Repaid ": "Repaid ",
          "Rejected ": "Rejected ",
          "All": "All",
          "Health, Tips & Tricks…": "Health, Tips & Tricks…",
          "Be aware of…": "Be aware of…",
          "All Videos": "All Videos",
          "Coffee shop tips": "Coffee shop tips",
          "Inactive": "Inactive",
          "Round Payment": "Round Payment",
          "Next Meeting Day": "Next Meeting Day",
          "Days": "Days",
          "Report": "Report",
          "Expenditure": "Expenditure",
          "Loan Priority List": "Loan Priority List",
          "Net Share": "Net Share",
          "Gross Share": "Gross Share",
          "contr": "contr",
          "Debt": "Debt",
          "Link with Banks": "Link with Banks",
          "Link": "Link",
          "Other Bank": "Other Bank",
          "Ready to link with the bank of your choice?":
              "Ready to link with the bank of your choice?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities",
          "Get Started": "Get Started",
          "Terms of service": "Terms of service",
          "Privacy policy": "Privacy policy",
          "Language": "Language",
          "Help and support": "Help and support",
          "Logout": "Logout",
          "Invalid phone number format": "Invalid phone number format",
          "Invalid password": "Invalid password",
          "Invalid username or password": "Invalid username or password",
          "Something went wrong, please Check your network connection":
              "Something went wrong, please Check your network connection",
          "press again to exit": "press again to exit",
          "First name is mandatory": "First name is mandatory",
          "Last name is mandatory": "Last name is mandatory",
          "Please agree with our policy and terms":
              "Please agree with our policy and terms",
          "Gender is a mandatory field": "Gender is a mandatory field",
          "Something went wrong, please try again":
              "Something went wrong, please try again",
          "Account Created Successfuly": "Account Created Successfuly",
          "This phone number is already registered":
              "This phone number is already registered",
          "Account creation failed please try again":
              "Account creation failed please try again",
          "Otp verified successfully": "Otp verified successfully",
          "This field is required": "This field is required",
          "Please enter only letters": "Please enter only letters",
          "Payment added Successfuly": "Payment added Successfuly",
          "payment process failed; please try again":
              "payment process failed; please try again",
          "Do you want to Logout": "Do you want to Logout",
          "Confirm Exit": "Confirm Exit",
          "Confirm Deletion": "Confirm Deletion",
          "Are you sure you want to delete this user":
              "Are you sure you want to delete this user",
          "Account Deleted Successfuly": "Account Deleted Successfuly",
          "Account Updated Successfuly": "Account Updated Successfuly",
          "Meeting created successfully": "Meeting created successfully",
          "Amount repaid Successfuly": "Amount repaid Successfuly",
          "Loan repayment failed; please try again":
              "Loan repayment failed; please try again",
          "please select a member": "please select a member",
          "please enter a loan amount": "please enter a loan amount",
          "The max amount of loan is": "The max amount of loan is",
          "Please enter a description": "Please enter a description",
          "please select a plan": "please select a plan",
          "Loan applied successfully": "Loan applied successfully",
          "Password must be at least 6 characters long":
              "Password must be at least 6 characters long",
          "Password unmatched": "Password unmatched",
          "Phone number is required": "Phone number is required",
          "Enter a valid phone number": "Enter a valid phone number",
          "Member added successfully": "Member added successfully",
          "Meeting type is required": "Meeting type is required",
          "Meeting inteval is required": "Meeting inteval is required",
          "Meeting activated successfully": "Meeting activated successfully",
          "Meeting edited successfully": "Meeting edited successfully",
          "Meeting deleted successfully": "Meeting deleted successfully",
          "Are you sure, This process is irreversible":
              "Are you sure, This process is irreversible",
          "Attendance saved successfully": "Attendance saved successfully",
          "Please fill attendace first": "Please fill attendace first",
          "No Penalties found": "No Penalties found",
          "Are you sure you want to add ..... Birr to ....":
              "Are you sure you want to add ..... Birr to ....",
          "Meeting closed successfully": "Meeting closed successfully",
          "Either Attendance has not been filled or payment is already done for ....":
              "Either Attendance has not been filled or payment is already done for ....",
          "Please fill attendance before any payment":
              "Please fill attendance before any payment",
        },
        //AMHARIC LANGUAGE
        'am_ET': {
          'English': 'አማርኛ',
          'Choose Language': 'ቋንቋ ይምረጡ',
          'Sign in to your account': 'ወደ አካውንትዎ ይግቡ',
          'Phone Number': 'ስልክ ቁጥር',
          'Pin': 'ምሥጢራዊ ቁጥር',
          'LOGIN': 'ግባ',
          "Don't have an account?": "አካውንት የለዎትም?",
          "SIGNUP": "ይመዝገቡ",
          "Create your account": "አካውንትዎን ይፍጠሩ",
          "First Name": "ስም",
          "Last Name": "የአባት ስም",
          "Select your Gender": "Select your Gender",
          "Male": "ወንድ",
          "Female": "ሴት",
          "Confirm Pin": "ምሥጢራዊ ቁጥሩን ያረጋግጡ",
          "Pin (Must be atleast 6 characters)":
              "ምሥጢራዊ ቁጥር (ቢያንስ 6 ካራክተር መሆን አለበት)",
          "Select an organization": "ድርጅት ይምረጡ",
          // "Confirm OTP": "Confirm OTP",
          "I understood the terms and policies.": "ሕግና ደንቦቹን ተረድቻለሁ።",
          "Have an account?": "አካውንት አለዎት?",
          // "If you didn't get the message tap the resend button bellow.":
          //     "If you didn't get the message tap the resend button bellow.",
          "Loanable Fund": "የብድር ፈንድ",
          "Bronze": "ነሐስ",
          "Silver": "ብር",
          "Gold": "ወርቅ",
          "Premium": "ፕሪሚየም",
          "Members": "አባላት",
          "Transactions": "ግብይቶች",
          "Loans": "ብድሮች",
          "Awareness": "ግንዛቤ",
          "Start": "ይጀምሩ",
          "Meetings": "ስብሰባዎች",
          "Tip of the day": "የዕለቱ ምክር",
          "stay informed": "አዳዲስ መረጃዎችን ያግኙ",
          "Recent updates": "የቅርብ ጊዜ መረጃዎች",
          "Total saving": "ጠቅላላ ቁጠባ",
          "Total Social Fund": "ጠቅላላ ማኅበራዊ ፈንድ",
          "Total Loan Disbursed": "ጠቅላላ የተከፈለ ብድር",
          "Total Loan Repayed": "ጠቅላላ የተመለሰ ብድር",
          "Total Social Fund released": "ጠቅላላ የተለቀቀ ማኅበራዊ ፈንድ",
          "Total members": "ጠቅላላ የአባላት ቁጥር",
          "Proxy": "ወኪል",
          "GROUP_ADMIN": "ቡድን አስተዳዳሪ",
          "Manager": "አስተዳዳሪ",
          "saving": "ቁጠባ",
          "Loan Despersal": "ብድር መልቀቅ",
          "Loan Repayment": "ብድር መመለስ",
          "Social Funds": "ማኅበራዊ ፈንዶች",
          "All Transactions": "ሁሉም ግብይቶች",
          "Pending ": "በሂደት ላይ",
          "Active": "በስራ ላይ",
          "Repaid ": "የተከፈለ",
          "Rejected ": "ውድቅ የተደረገ",
          "All": "ሁሉም",
          "Health, Tips & Tricks…": "ጤና፣ ምክሮችና ብልሃቶች…",
          "Be aware of…": "ከ…ጥንቃቄ ያድርጉ",
          "All Videos": "ሁሉም ቪዲዮዎች",
          "Coffee shop tips": "የሻይ ቡና ቤት ምክሮች ",
          "Inactive": "የማይሰራ",
          "Round Payment": "የዙር ክፍያ",
          "Next Meeting Day": "ቀጣይ የስብሰባ ቀን",
          "Days": "ቀናት",
          "Report": "ሪፖርት",
          "Expenditure": "ወጪ",
          "Loan Priority List": "ቅድሚያ የሚሰጠው የብድር ዝርዝር",
          "Net Share": "የተጣራ ድርሻ",
          "Gross Share": "ጠቅላላ ድርሻ",
          "contr": "አስተዋጽዖ",
          "Debt": "እዳ",
          "Link with Banks": "ከባንኮች ጋር ትስስር ፍጠር",
          "Link": "ትስስር",
          "Other Bank": "ሌላ ባንክ",
          "Ready to link with the bank of your choice?":
              "ከሚፈልጉት ባንክ ጋር ለመተሳሰር ዝግጁ ነዎት?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "ባንኮች እርስዎ የሚያደርጓቸውን የፋይናንስ ግብይቶች መዝግበው የሚይዙ ሲሆን ይህም በተለይ ብድር፣ የገንዘብ ድጋፍ ወይም ሌሎች የፋይናንስ እድሎችን ለማግኘት በሚያመለክቱበት ወቅት ጠቃሚ ነው።",
          "Get Started": "እንጀምር",
          "Terms of service": "ደንብና ሁኔታዎች",
          "Privacy policy": "የግል መረጃ ጥበቃ ፖሊሲ",
          "Language": "ቋንቋ",
          "Help and support": "እርዳታና ድጋፍ",
          "Logout": "ይውጡ",
          "Invalid phone number format": "የተሳሳተ የስልክ ቁጥር አጻጻፍ ተጠቅመዋል",
          "Invalid password": "የተሳሳተ የይለፍ ቃል",
          "Invalid username or password": "የተሳሳተ ዩዘርኔም ወይም የይለፍ ቃል አስገብተዋል",
          "Something went wrong, please Check your network connection":
              "የሆነ ችግር ተፈጥሯል። እባክዎ የኢንተርኔት ግንኙነት መኖሩን ያረጋግጡ። ",
          "press again to exit": "ለመውጣት ደግመው ይጫኑ",
          "First name is mandatory": "ስምዎን ማስገባት አለብዎት",
          "Last name is mandatory": "የአባትዎን ስም ማስገባት አለብዎት",
          "Please agree with our policy and terms":
              "የተሳሳተ የስልክ ቁጥር አጻጻፍ ተጠቅመዋል",
          "Gender is a mandatory field": "ጾታ ማስገባት አለብዎት",
          "Something went wrong, please try again":
              "የሆነ ችግር ተፈጥሯል። እባክዎ እንደገና ይሞክሩ",
          "Account Created Successfuly": "አካውንትዎ በተሳካ ሁኔታ ተፈጥሯል",
          "This phone number is already registered":
              "ይህ የስልክ ቁጥር ቀድሞውኑ የተመዘገበ ነው",
          "Account creation failed please try again":
              "አካውንት መፍጠር አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "Otp verified successfully": "ጊዜያዊ የይለፍ ቃሉን አረጋግጠናል",
          "This field is required": "ይሄ ቦታ መሞላት አለበት",
          "Please enter only letters": "እባክዎ ፊደል ብቻ ያስገቡ",
          "Payment added Successfuly": "ክፍያው እንዲገባ ተደርጓል",
          "payment process failed; please try again":
              "ክፍያውን ማጠናቀቅ አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "Do you want to Logout": "ዘግተው መውጣት ይፈልጋሉ?",
          "Confirm Exit": "መውጣት እንደሚፈልጉ ያረጋግጡ",
          "Confirm Deletion": "መሰረዝ እንደሚፈልጉ ያረጋግጡ",
          "Are you sure you want to delete this user?":
              "እርግጠኛ ነዎት ይህን ተጠቃሚ መሰረዝ ይፈልጋሉ?",
          "Account Deleted Successfuly": "አካውንቱ ተሰርዟል",
          "Account Updated Successfuly": "አካውንቱ ተሻሽሏል",
          "Meeting created successfully": "የስብሰባ ጊዜ ሠሌዳ ተፈጥሯል",
          "Amount repaid Successfuly": "ገንዘቡ ተከፍሏል",
          "Loan repayment failed; please try again":
              "ብድሩን መክፈል አልተቻለም። እባክዎ እንደገና ይሞክሩ",
          "please select a member": "እባክዎ አባል ይምረጡ",
          "please enter a loan amount": "እባክዎ የብድሩን መጠን ያስገቡ",
          "The max amount of loan is": "ከፍተኛው የብድር መጠን ------- ነው",
          "Please enter a description": "እባክዎ መግለጫ ያስገቡ",
          "please select a plan": "እባክዎ እቅድ ይምረጡ",
          "Loan applied successfully": "ብድሩ በትክክል ተልል",
          "Password must be at least 6 characters long":
              "የይለፍ ቃል ቢያንስ 6 ፊደል መሆን አለበት",
          "Password unmatched": "ያስገቡት የይለፍ ቃል የተለያየ ነው",
          "Phone number is required": "ስልክ ቁጥር መሞላት አለበት",
          "Enter a valid phone number": "ትክክለኛ ስልክ ቁጥር ያስገቡ",
          "Member added successfully": "አባል በትክክል ተጨምሯል",
          "Meeting type is required": "የስብሰባው ዓይነት መሞላት አለበት",
          "Meeting inteval is required": "የስብሰባው መጀመሪያና ማብቂያ መሞላት አለበት",
          "Meeting activated successfully": "የስብሰባ ጊዜ ሠሌዳ እንዲሠራ ተደርጓል",
          "Meeting edited successfully": "የስብሰባ ጊዜ ሠሌዳ ተስተካክሏል",
          "Meeting deleted successfully": "የስብሰባ ጊዜ ሠሌዳ ተሰርዟል",
          "Are you sure, This process is irreversible":
              "እርግጠኛ ነዎት? ይህን ሂደት ማቋረጥ አይቻልም",
          "Attendance saved successfully": "አቴንዳንስ እንዲቀመጥ ተደርጓል",
          "Please fill attendace first": "እባክዎ መጀመሪያ አቴንዳንስ ይሙሉ",
          "No Penalties found": "ቅጣት የተጣለበት ሰው የለም",
          "Are you sure you want to add ..... Birr to ....":
              "እርግጠኛ ነዎት ..... ብር ወደ .... መጨመር ይፈልጋሉ?",
          "Meeting closed successfully": "ስብሰባ በትክክል ተዘግቷል",
          "Either Attendance has not been filled or payment is already done for ....":
              "ለ .... ወይ አቴንዳንስ አልተሞላም አልያም ክፍያ ተፈጽሟል",
          "Please fill attendance before any payment":
              "እባክዎ ምንም ዓይነት ክፍያ ከመፈጸምዎ በፊት አቴንዳንስ ይሙሉ",
        },
        //KANNADA LANGUAGE
        'or_ET': {
          'LOGIN': 'Senaa',
          'Phone Number': 'Lakkoofsa Bilbilaa',
          'Password': 'Jecha iccitii',
          'Forgot': 'Password dagadheera?',
          "Don't have an account? ": "Akkaawuntii hin qabduu? ",
          "SIGNUP here": "Galmaa'aa",
          "SIGNUP": "Galmaa'i",
          "First Name*": "Maqaa jalqabaa*",
          "Last Name": "Maqaa Abbaa",
          "Phone Number*": "Lakkoofsa Bilbilaa*",
          "Password*": "Jecha iccitii*",
          "Confirm Password*": "Password Mirkaneessi*",
          "Confirm Password": "Password Mirkaneessi",
          "Referal Code": "Koodii Rifaralaa",
          "Confirm OTP": "OTP Mirkaneessuu",
          "Reset": "Reset gochuu",
          "Confirm": "Mirkaneessuu",
          "Reset Password": "Jecha Darbii Irra Deebi'i",
          "New Password": "jecha icciitii haaraa",
          "Resend": "Irra deebiin ergaa",
          "If you didn't get the message tap the resend button bellow.":
              "Yoo ergaan sun hin arganne ta'e button resend armaan gadii tuqi.",
          "Hello, Register here to get started!":
              "Akkam jirtu, Jalqabuuf asitti galmaa'aa!",
          "Privacy and Security": "Dhuunfaa fi Nageenya",
          "About Us": "Waa'ee Keenya",
          "Change Password": "Jecha Darbii Jijjiiri",
          "Change Language": "Afaan Jijjiirraa",
          "Change Location": "Bakka Jijjiirraa",
          "Logout": "Ba'i",
          "Email": "Imeelii",
          "Dark Theme": "Mata Dukkana ",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "Ni uuma. Lakkoofsa bilbilaa akkaawuntii keessan waliin walqabate galchaa",
          "Send OTP": "OTP ergaa",
          "OTP Verification": "Mirkaneessa OTP",
          "Enter the verification code we just sent to your mobile phone":
              "Koodii mirkaneessaa amma moobaayila keessaniif erginee galchaa",
          "Verify OTP": "OTP mirkaneessi",
          "Create new password?": "Jecha icciitii haaraa uumuu?",
          "Confirm Exit": "Ba'uu Mirkaneessi",
          "Do you want to Logout?": "Logout gochuu barbaaddaa?",
          "Yes": "Eeyyee",
          "No": "Lakki",
          "Latest": "Kan dhiyeenyaa",
          "Menu": "Filannoo",
          "Challenges": "Taphoota",
          "Convert Coins": "Saantima Jijjiirraa",
          "Share": "Qoodi",
          "Help": "Gargaarsa",
          "Rate us": "Nuuf madaala",
          "Other products": "Oomishaalee Biroo",
          "Messages": "Ergaawwan",
          "New message1": "Ergaa haaraa1",
          "New message2": "Ergaa haaraa2",
          "New message3": "Ergaa haaraa3",
          "New message4": "Ergaa haaraa4",
          "New feature is unlocked": "Amalli haaraan banameera",
          "Total Golden Coins": "Waliigala Saantima Goldani",
          "Total ATM Coins": "Waliigala Saantima ATM",
          "Total Wallet Coins": "Waliigala Saantima Wallet",
          "Total MB Coins": "Waliigala Saantima MB",
          "Total P Coins": "Waliigala Saantima P",
          "Total PC Coins": "Waliigala Saantima PC",
          "Total PV Coins": "Waliigala Saantima PV",
          "  You have 4.2 Golden coins  ": "  Saantima Golden 4.2 qabda  ",
          "Convert": "Jijjiiruu",
          "Locations": "Bakkeewwan",
          "Register": "Galmeessi",
          "Languages": "Afaanota",
        }
      };
}
