import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'sign in to your account': 'sign in to your account',
          'Phone Number': 'Phone Number',
          'Pin': 'Pin',
          'Login': 'Login',
          "Don't have an account? ": "Don't have an account? ",
          "Signup": "Signup",
          "Create your account": "Create your account",
          "First Name*": "First Name*",
          "Last Name": "Last Name",
          "Male": "Male",
          "Female": "Female",
          "Confirm Pin": "Confirm Pin",
          "Pin(Must be atleast 6 characters)":
              "Pin(Must be atleast 6 characters)",
          "Select an organization": "Select an organization",
          "Confirm OTP": "Confirm OTP",
          "I understood the terms and policies.":
              "I understood the terms and policies.",
          "Have an account?": "Have an account?",
          "If you didn't get the message tap the resend button bellow.":
              "If you didn't get the message tap the resend button bellow.",
          "Loanable Fund": "Loanable Fund",
          "Bronze": "Bronze",
          "Silver": "Silver",
          "Gold": "Gold",
          "Premium": "Premium",
          "Members": "Members",
          "Transactions": "Transactions",
          "Loans": "Loans",
          "Awareness": "Awareness",
          "Start": "Start",
          "Meetings": "Meetings",
          "Tip of the day": "Tip of the day",
          "stay informed": "stay informed",
          "Recent updates": "Recent updates",
          "Total saving": "Total saving",
          "Total Social Fund": "Total Social Fund",
          "Total Loan Disbursed": "Total Loan Disbursed",
          "Total Loan Repayed": "Total Loan Repayed",
          "Total Social Fund released": "Total Social Fund released",
          "Total members": "Total members",
          "Proxy": "Proxy",
          "GROUP_ADMIN": "GROUP_ADMIN",
          "Manager": "Manager",
          "saving": "saving",
          "Loan Despersal": "Loan Despersal",
          "Loan Repayment": "Loan Repayment",
          "Social Funds": "Social Funds",
          "All Transactions": "All Transactions",
          "Pending ": "Pending ",
          "Active": "Active",
          "Repaid ": "Repaid ",
          "Rejected ": "Rejected ",
          "All": "All",
          "Health, Tips & Tricks…": "Health, Tips & Tricks…",
          "Be aware of…": "Be aware of…",
          "All Videos": "All Videos",
          "Coffee shop tips": "Coffee shop tips",
          "Inactive": "Inactive",
          "Round Payment": "Round Payment",
          "Next Meeting Day": "Next Meeting Day",
          "Days": "Days",
          "Report": "Report",
          "Expenditure": "Expenditure",
          "Loan Priority List": "Loan Priority List",
          "Net Share": "Net Share",
          "Gross Share": "Gross Share",
          "contr": "contr",
          "Debt": "Debt",
          "Link with Banks": "Link with Banks",
          "Link": "Link",
          "Other Bank": "Other Bank",
          "Ready to link with the bank of your choice?":
              "Ready to link with the bank of your choice?",
          "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities":
              "Banks keep a record of your financial transactions, which can be especially useful when applying for loans, grants, or other financial opportunities",
          "Get Started": "Get Started",
          "Terms of service": "Terms of service",
          "Privacy policy": "Privacy policy",
          "Language": "Language",
          "Help and support": "Help and support",
          "Logout": "Logout",
          "Invalid phone number format": "Invalid phone number format",
          "Invalid password": "Invalid password",
          "Invalid username or password": "Invalid username or password",
          "Something went wrong, please Check your network connection":
              "Something went wrong, please Check your network connection",
          "press again to exit": "press again to exit",
          "First name is mandatory": "First name is mandatory",
          "Last name is mandatory": "Last name is mandatory",
          "Please agree with our policy and terms":
              "Please agree with our policy and terms",
          "Gender is a mandatory field": "Gender is a mandatory field",
          "Something went wrong, please try again":
              "Something went wrong, please try again",
          "Account Created Successfuly": "Account Created Successfuly",
          "This phone number is already registered":
              "This phone number is already registered",
          "Account creation failed please try again":
              "Account creation failed please try again",
          "Otp verified successfully": "Otp verified successfully",
          "This field is required": "This field is required",
          "Please enter only letters": "Please enter only letters",
          "Payment added Successfuly": "Payment added Successfuly",
          "payment process failed; please try again":
              "payment process failed; please try again",
          "Do you want to Logout": "Do you want to Logout",
          "Confirm Exit": "Confirm Exit",
          "Confirm Deletion": "Confirm Deletion",
          "Are you sure you want to delete this user":
              "Are you sure you want to delete this user",
          "Account Deleted Successfuly": "Account Deleted Successfuly",
          "Account Updated Successfuly": "Account Updated Successfuly",
          "Meeting created successfully": "Meeting created successfully",
          "Amount repaid Successfuly": "Amount repaid Successfuly",
          "Loan repayment failed; please try again":
              "Loan repayment failed; please try again",
          "please select a member": "please select a member",
          "please enter a loan amount": "please enter a loan amount",
          "The max amount of loan is": "The max amount of loan is",
          "Please enter a description": "Please enter a description",
          "please select a plan": "please select a plan",
          "Loan applied successfully": "Loan applied successfully",
          "Password must be at least 6 characters long":
              "Password must be at least 6 characters long",
          "Password unmatched": "Password unmatched",
          "Phone number is required": "Phone number is required",
          "Enter a valid phone number": "Enter a valid phone number",
          "Member added successfully": "Member added successfully",
          "Meeting type is required": "Meeting type is required",
          "Meeting inteval is required": "Meeting inteval is required",
          "Meeting activated successfully": "Meeting activated successfully",
          "Meeting edited successfully": "Meeting edited successfully",
          "Meeting deleted successfully": "Meeting deleted successfully",
          "Are you sure, This process is irreversible":
              "Are you sure, This process is irreversible",
          "Attendance saved successfully": "Attendance saved successfully",
          "Please fill attendace first": "Please fill attendace first",
          "No Penalties found": "No Penalties found",
          "Are you sure you want to add ..... Birr to ....":
              "Are you sure you want to add ..... Birr to ....",
          "Meeting closed successfully": "Meeting closed successfully",
          "Either Attendance has not been filled or payment is already done for ....":
              "Either Attendance has not been filled or payment is already done for ....",
          "Please fill attendance before any payment":
              "Please fill attendance before any payment",
        },
        //HINDI LANGUAGE
        'am_ET': {
          'Login': 'ግባ',
          'Phone Number': 'ስልክ ቁጥር',
          'Password': 'የይለፍ ቃል',
          'Forgot': 'መክፈቻ ቁልፉን ረሳኽው?',
          "Don't have an account? ": "መለያ የለዎትም? ",
          "Signup here": "እዚህ ይመዝገቡ",
          "Signup": "ክፈት",
          "First Name*": "የመጀመሪያ ስም*",
          "Last Name": "ያባት ስም",
          "Phone Number*": "ስልክ ቁጥር*",
          "Password*": "የይለፍ ቃል*",
          "Confirm Password*": "የይለፍ ቃል አረጋግጥ*",
          "Confirm Password": "የይለፍ ቃል አረጋግጥ",
          "Reset Password": "የይለፍ ቃል ዳግም አስጀምር",
          "New Password": "አዲስ የይለፍ ቃል",
          "Referal Code": "ሪፈራል ኮድ",
          "Confirm OTP": "OTP ያረጋግጡ",
          "Confirm": "ያረጋግጡ",
          "Reset": "ዳግም አስጀምር",
          "Resend": "እንደገና ላክ",
          "If you didn't get the message tap the resend button bellow.":
              "መልእክቱ ካልደረሰዎት ከታች ያለውን የዳግም ላክ ቁልፍ ይንኩ።",
          "Hello, Register here to get started!": "ሰላም, ለመጀመር እዚህ ይመዝገቡ!",
          "Privacy and Security": "ግላዊነት እና ደህንነት",
          "About Us": "ስለ እኛ",
          "Change Password": "የሚስጥር ቁልፍ ይቀይሩ",
          "Change Language": "ቋንቋ ቀይር",
          "Change Location": "አካባቢን ቀይር",
          "Logout": "ውጣ",
          "Email": "ኢሜይል",
          "Dark Theme": "ጨለማ ጭብጥ",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "ይከሰታል። እባክዎ ከመለያዎ ጋር የተገናኘውን ስልክ ቁጥር ያስገቡ",
          "Send OTP": "OTP ላክ",
          "OTP Verification": "የኦቲፒ ማረጋገጫ",
          "Enter the verification code we just sent to your mobile phone":
              "አሁን ወደ ሞባይል ስልኮ የላክነውን የማረጋገጫ ኮድ ያስገቡ",
          "Verify OTP": "ኦቲፒን ያረጋግጡ",
          "Create new password?": "አዲስ የይለፍ ቃል ይፍጠሩ?",
          "Confirm Exit": "መውጣትን ያረጋግጡ",
          "Do you want to Logout?": "መውጣት ትፈልጋለህ?",
          "Yes": "አዎ",
          "No": "አይ",
          "Latest": "የቅርብ ጊዜ",
          "Menu": "ምናሌ",
          "Challenges": "ጨዋታዎች",
          "Convert Coins": "ሳንቲሞችን ይለውጡ",
          "Share": "አጋራ",
          "Help": "እገዛ",
          "Rate us": "ደረጃ ይስጡን",
          "Other products": "ሌሎች ምርቶች",
          "Messages": "መልዕክቶች",
          "New message1": "አዲስ መልእክት1",
          "New message2": "አዲስ መልእክት2",
          "New message3": "አዲስ መልእክት3",
          "New message4": "አዲስ መልእክት4",
          "New feature is unlocked": "አዲስ ባህሪ ተከፍቷል።",
          "Total Golden Coins": "ጠቅላላ Golden ሳንቲሞች",
          "Total ATM Coins": "ጠቅላላ ATM ሳንቲሞች",
          "Total Wallet Coins": "ጠቅላላ Wallet ሳንቲሞች",
          "Total MB Coins": "ጠቅላላ MB ሳንቲሞች",
          "Total P Coins": "ጠቅላላ P ሳንቲሞች",
          "Total PC Coins": "ጠቅላላ PC ሳንቲሞች",
          "Total PV Coins": "ጠቅላላ PV ሳንቲሞች",
          "  You have 4.2 Golden coins  ": "  4.2 Golden ሳንቲሞች አሎት  ",
          "Convert": "ቀይር",
          "Locations": "ቦታዎች",
          "Register": "ይመዝገቡ",
          "Languages": "ቋንቋዎች",
        },
        //KANNADA LANGUAGE
        'or_ET': {
          'Login': 'Senaa',
          'Phone Number': 'Lakkoofsa Bilbilaa',
          'Password': 'Jecha iccitii',
          'Forgot': 'Password dagadheera?',
          "Don't have an account? ": "Akkaawuntii hin qabduu? ",
          "Signup here": "Galmaa'aa",
          "Signup": "Galmaa'i",
          "First Name*": "Maqaa jalqabaa*",
          "Last Name": "Maqaa Abbaa",
          "Phone Number*": "Lakkoofsa Bilbilaa*",
          "Password*": "Jecha iccitii*",
          "Confirm Password*": "Password Mirkaneessi*",
          "Confirm Password": "Password Mirkaneessi",
          "Referal Code": "Koodii Rifaralaa",
          "Confirm OTP": "OTP Mirkaneessuu",
          "Reset": "Reset gochuu",
          "Confirm": "Mirkaneessuu",
          "Reset Password": "Jecha Darbii Irra Deebi'i",
          "New Password": "jecha icciitii haaraa",
          "Resend": "Irra deebiin ergaa",
          "If you didn't get the message tap the resend button bellow.":
              "Yoo ergaan sun hin arganne ta'e button resend armaan gadii tuqi.",
          "Hello, Register here to get started!":
              "Akkam jirtu, Jalqabuuf asitti galmaa'aa!",
          "Privacy and Security": "Dhuunfaa fi Nageenya",
          "About Us": "Waa'ee Keenya",
          "Change Password": "Jecha Darbii Jijjiiri",
          "Change Language": "Afaan Jijjiirraa",
          "Change Location": "Bakka Jijjiirraa",
          "Logout": "Ba'i",
          "Email": "Imeelii",
          "Dark Theme": "Mata Dukkana ",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "Ni uuma. Lakkoofsa bilbilaa akkaawuntii keessan waliin walqabate galchaa",
          "Send OTP": "OTP ergaa",
          "OTP Verification": "Mirkaneessa OTP",
          "Enter the verification code we just sent to your mobile phone":
              "Koodii mirkaneessaa amma moobaayila keessaniif erginee galchaa",
          "Verify OTP": "OTP mirkaneessi",
          "Create new password?": "Jecha icciitii haaraa uumuu?",
          "Confirm Exit": "Ba'uu Mirkaneessi",
          "Do you want to Logout?": "Logout gochuu barbaaddaa?",
          "Yes": "Eeyyee",
          "No": "Lakki",
          "Latest": "Kan dhiyeenyaa",
          "Menu": "Filannoo",
          "Challenges": "Taphoota",
          "Convert Coins": "Saantima Jijjiirraa",
          "Share": "Qoodi",
          "Help": "Gargaarsa",
          "Rate us": "Nuuf madaala",
          "Other products": "Oomishaalee Biroo",
          "Messages": "Ergaawwan",
          "New message1": "Ergaa haaraa1",
          "New message2": "Ergaa haaraa2",
          "New message3": "Ergaa haaraa3",
          "New message4": "Ergaa haaraa4",
          "New feature is unlocked": "Amalli haaraan banameera",
          "Total Golden Coins": "Waliigala Saantima Goldani",
          "Total ATM Coins": "Waliigala Saantima ATM",
          "Total Wallet Coins": "Waliigala Saantima Wallet",
          "Total MB Coins": "Waliigala Saantima MB",
          "Total P Coins": "Waliigala Saantima P",
          "Total PC Coins": "Waliigala Saantima PC",
          "Total PV Coins": "Waliigala Saantima PV",
          "  You have 4.2 Golden coins  ": "  Saantima Golden 4.2 qabda  ",
          "Convert": "Jijjiiruu",
          "Locations": "Bakkeewwan",
          "Register": "Galmeessi",
          "Languages": "Afaanota",
        }
      };
}
